title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Theresa
email: theresa.siefert@stud.fhgr.ch
description: > # this means to ignore newlines
   Lerntagebuch des Kurs Bibliotheks- und Archivinformatik FS2023



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
